apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: uforetrygd-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" #SAKSBEHANDLER
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" #BRUKERHJELPA
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" #VEILEDER
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" #OKONOMI
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0" #STRENGT_FORTROLIG
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" #FORTROLIG
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" #EGENANSATT
  tokenx:
    enabled: true
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: uforetrygd-frontend-veileder
          namespace: pensjonselvbetjening
          cluster: prod-gcp
        - application: uforetrygd-frontend-borger
          namespace: pensjonselvbetjening
          cluster: prod-gcp
    outbound:
      rules:
        - application: pensjon-pid-encryption
          namespace: pensjon-person
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: pensjon-pen.prod-fss-pub.nais.io
        - host: pensjon-representasjon.prod-fss-pub.nais.io
  env:
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: FULLMAKT_URL
      value: https://pensjon-representasjon.prod-fss-pub.nais.io
    - name: FULLMAKT_SCOPE
      value: api://prod-fss.pensjon-person.pensjon-representasjon/.default
    - name: FULLMAKT_AUDIENCE
      value: prod-fss:pensjon-person:pensjon-representasjon
    - name: PARALLELLE_SANNHETER_URL
      value: https://pensjon-parallelle-sannheter.intern.nav.no
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: prod-fss:pdl:pdl-api
    - name: PEN_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io
    - name: PEN_SCOPE
      value: api://prod-fss.pensjondeployer.pensjon-pen/.default
    - name: PEN_AUDIENCE
      value: prod-fss:pensjondeployer:pensjon-pen
    - name: PERSONDATA_URL
      value: https://pensjon-persondata.prod-fss-pub.nais.io
    - name: PERSONDATA_SCOPE
      value: api://prod-fss.pensjon-person.pensjon-persondata/.default
    - name: PERSONDATA_AUDIENCE
      value: prod-fss:pensjon-person:pensjon-persondata
    - name: SKJERMING_URL
      value: https://skjermede-personer-pip.intern.nav.no
    - name: SKJERMING_SCOPE
      value: api://prod-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMET_TILGANG_GROUP_ID
      value: e750ceb5-b70b-4d94-b4fa-9d22467b786b
    - name: FORTROLIG_TILGANG_GROUP_ID
      value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    - name: STRENGT_FORTROLIG_TILGANG_GROUP_ID
      value: ad7b87a6-9180-467c-affc-20a566b0fec0
    - name: BRUKERHJELPA_GROUP_ID
      value: 7845a796-1516-4d14-b500-fd65c001f35c
    - name: OKONOMI_GROUP_ID
      value: 70ef8e7f-7456-4298-95e0-b13c0ef2422b
    - name: SAKSBEHANDLER_GROUP_ID
      value: 0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e
    - name: VEILEDER_GROUP_ID
      value: 959ead5b-99b5-466b-a0ff-5fdbc687517b
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: SAF_AUDIENCE
      value: prod-fss:teamdokumenthandtering:saf
    - name: SAF_SELVBETJENING_URL
      value: https://safselvbetjening.prod-fss-pub.nais.io
    - name: SAF_SELVBETJENING_SCOPE
      value: api://prod-fss.teamdokumenthandtering.safselvbetjening/.default
    - name: SAF_SELVBETJENING_AUDIENCE
      value: prod-fss:teamdokumenthandtering:safselvbetjening
    - name: PID_ENCRYPTION_URL
      value: http://pensjon-pid-encryption.pensjon-person
    - name: PID_ENCRYPTION_SCOPE
      value: api://prod-gcp.pensjon-person.pensjon-pid-encryption/.default