apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: din-uforetrygd-frontend-borger
  namespace: ufore
  labels:
    team: ufore
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{ image }}"
  ingresses:
    - https://uforetrygd-borger.intern.dev.nav.no/din-uforetrygd/selvbetjening
    - https://uforetrygd-borger.ansatt.dev.nav.no/din-uforetrygd/selvbetjening
    - https://uforetrygd-selvbetjening-frontend-borger.intern.dev.nav.no/uforetrygd/selvbetjening
    - https://uforetrygd-selvbetjening-frontend-borger.ansatt.dev.nav.no/uforetrygd/selvbetjening
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /uforetrygd/selvbetjening/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /uforetrygd/selvbetjening/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  idporten:
    enabled: true
    sidecar:
      level: idporten-loa-substantial
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    frontend:
      enabled: true
    logging:
      destinations:
        - id: elastic
        - id: loki
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator # only in dev
          namespace: nais
        - application: azure-token-generator # only in dev
          namespace: nais
        - application: wonderwalled-idporten # only in dev
          namespace: nais
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: din-uforetrygd-backend
          namespace: ufore
        - application: ufore-varsler
          namespace: ufore
      external:
        - host: ufore-unleash-api.nav.cloud.nais.io
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  env:
    - name: MODE
      value: borger
    - name: DECORATOR_ENV
      value: dev
    - name: DIN_UFORETRYGD_BACKEND
      value: http://din-uforetrygd-backend
    - name: UFORE_VARSLER
      value: http://ufore-varsler
    - name: LINK_SOKNAD_GRADERT_UFORE
      value: https://skjemadelingslenke.ekstern.dev.nav.no/fyllut/nav120901
    - name: LINK_SOKNAD_UFORE
      value: https://skjemadelingslenke.ekstern.dev.nav.no/fyllut/nav120605
    - name: LINK_SOKNAD_BARNETILLEGG
      value: https://skjemadelingslenke.ekstern.dev.nav.no/fyllut/nav121501
    - name: LINK_LES_MER_OM_UFORETRYGD
      value: https://www.ansatt.dev.nav.no/uforetrygd
    - name: LINK_ENDRE_KONTONUMMER
      value: https://www.ansatt.dev.nav.no/person/personopplysninger/nb/#utbetaling
    - name: LINK_PERSONOPPLYSNINGER
      value: https://www.ansatt.dev.nav.no/person/personopplysninger
    - name: LINK_OKONOMISKE_TILLEGG
      value: https://www.ansatt.dev.nav.no/uforetrygd#tillegg
    - name: LINK_KLAGE
      value: https://www.ansatt.dev.nav.no/person/kontakt-oss/tilbakemeldinger
    - name: LINK_MELD_FRA_OM_ENDRINGER
      value: https://www.ansatt.dev.nav.no/uforetrygd#melde
    - name: LINK_UTBETALINGER
      value: https://www.intern.dev.nav.no/utbetalingsoversikt
    - name: LINK_BREV
      value: https://pensjon-pselv-q2-gcp.ansatt.dev.nav.no/pselv/publisering/dininnboks.jsf?context=ut&simpleMode=true
    - name: LINK_INNTEKTSPLANLEGGER
      value: https://borger.ansatt.dev.nav.no/uforetrygd/selvbetjening/inntektsplanleggeren
    - name: LINK_SAKER
      value: https://pensjon-pselv-q2-gcp.ansatt.dev.nav.no/pselv/publisering/saksoversikt.jsf?context=ut&simpleMode=true
    - name: LINK_SKATTETREKK
      value: https://sokos-frivillig-skattetrekk-frontend-q2.intern.dev.nav.no/utbetalinger/frivillig-skattetrekk
    - name: LINK_FAMILIEFORHOLD
      value: https://pensjon-selvbetjening-familieforhold-frontend-borger-q2.intern.dev.nav.no/pensjon/selvbetjening/familieforhold/?context=ut
    - name: LINK_FULLMAKTER
      value: https://www.intern.dev.nav.no/person/pdl-fullmakt-ui
    - name: LINK_BPROF_FULLMAKTER
      value: https://bytt-bruker-frontend-borger-q2.ansatt.dev.nav.no/pensjon/selvbetjening/bytt-bruker/pensjonfullmakt
    - name: LINK_ETTERSENDE
      value: https://www.ansatt.dev.nav.no/ettersende#uforetrygd
    - name: LINK_SAKSBEHANDLINGSTIDER_UFORETRYGD
      value: https://www.ansatt.dev.nav.no/saksbehandlingstider#uforetrygd
    - name: LINK_DITT_LOKALE_NAV_KONTOR
      value: https://www.ansatt.dev.nav.no/no/nav-og-samfunn/kontakt-nav/relatert-informasjon/finn-ditt-nav-kontor
    - name: LINK_REGELVERKSENDRINGER
      value: https://www.nav.no/regelendring-uforetrygd
    - name: LINK_DOKUMENTOVERSIKT
      value: https://www.ansatt.dev.nav.no/dokumentarkiv
    - name: LINK_REPRESENTASJON_TILLEGGSDATA
      value: https://borger.ansatt.dev.nav.no/representasjon-tilleggsdata
    - name: DIN_UFORETRYGD_BACKEND_SCOPE
      value: dev-gcp:ufore:din-uforetrygd-backend
    - name: UFORE_VARSLER_SCOPE
      value: dev-gcp:ufore:ufore-varsler
    - name: REPRESENTASJON_BANNER
      value: https://representasjon-banner-frontend-borger-q2.ekstern.dev.nav.no/pensjon/selvbetjening/representasjon
    - name: UNLEASH_SERVER_API_URL
      value: https://ufore-unleash-api.nav.cloud.nais.io/api
    - name: NEXT_PUBLIC_FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
  envFrom:
    - secret: din-uforetrygd-frontend-unleash-api-token