apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: din-uforetrygd-frontend-veileder
  namespace: ufore
  labels:
    team: ufore
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{ image }}"
  ingresses:
    - https://uforetrygd-veileder.intern.dev.nav.no/din-uforetrygd/selvbetjening
    - https://uforetrygd-veileder.ansatt.dev.nav.no/din-uforetrygd/selvbetjening
    - https://uforetrygd-selvbetjening-frontend-veileder.intern.dev.nav.no/uforetrygd/selvbetjening
    - https://uforetrygd-selvbetjening-frontend-veileder.ansatt.dev.nav.no/uforetrygd/selvbetjening
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /uforetrygd/selvbetjening/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /uforetrygd/selvbetjening/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    sidecar:
      autoLogin: true
      enabled: true
    application:
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "9e122ddd-e542-4cc1-a7eb-92c99140fe0e" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "05ae245b-7b47-428a-9074-4ff6b59eddbc" # 0000-GA-Pensjon_Okonomi
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "a3f91493-1ab8-4b64-a544-0a77cbba9240" # 0000-GA-Pensjon_VEILEDER
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator # only in dev
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: din-uforetrygd-backend
          cluster: dev-gcp
          namespace: ufore
        - application: ufore-varsler
          namespace: ufore
      external:
        - host: ufore-unleash-api.nav.cloud.nais.io
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  env:
    - name: MODE
      value: veileder
    - name: DECORATOR_ENV
      value: dev
    - name: DIN_UFORETRYGD_BACKEND
      value: http://din-uforetrygd-backend
    - name: UFORE_VARSLER
      value: http://ufore-varsler
    - name: LINK_SOKNAD_GRADERT_UFORE
      value: https://skjemadelingslenke.ekstern.dev.nav.no/fyllut/nav120901?sub=paper
    - name: LINK_SOKNAD_UFORE
      value: https://skjemadelingslenke.ekstern.dev.nav.no/fyllut/nav120605?sub=paper
    - name: LINK_SOKNAD_BARNETILLEGG
      value: https://skjemadelingslenke.ekstern.dev.nav.no/fyllut/nav121501?sub=paper
    - name: LINK_LES_MER_OM_UFORETRYGD
      value: https://www.ansatt.dev.nav.no/uforetrygd
    - name: LINK_ENDRE_KONTONUMMER
      value: https://www.ansatt.dev.nav.no/person/personopplysninger/nb/#utbetaling
    - name: LINK_PERSONOPPLYSNINGER
      value: https://www.ansatt.dev.nav.no/person/personopplysninger
    - name: LINK_OKONOMISKE_TILLEGG
      value: https://www.ansatt.dev.nav.no/uforetrygd#tillegg
    - name: LINK_KLAGE
      value: https://www.ansatt.dev.nav.no/person/kontakt-oss/tilbakemeldinger
    - name: LINK_MELD_FRA_OM_ENDRINGER
      value: https://www.ansatt.dev.nav.no/uforetrygd#melde
    - name: LINK_UTBETALINGER
      value: https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/mineutbetalinger.jsf?simpleMode=true&_brukerId=PID&_loggedOnName=USER&context=ut
    - name: LINK_BREV
      value: https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/dininnboks.jsf?context=ut&_brukerId=PID&_loggedOnName=USER&simpleMode=true
    - name: LINK_INNTEKTSPLANLEGGER
      value: https://veileder.ansatt.dev.nav.no/uforetrygd/selvbetjening/inntektsplanleggeren?pid=PID
    - name: LINK_SAKER
      value: https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/saksoversikt.jsf?context=ut&_brukerId=PID&_loggedOnName=USER&simpleMode=true
    - name: LINK_SKATTETREKK
      value: https://sokos-frivillig-skattetrekk-frontend-q2.ansatt.dev.nav.no/utbetaling/skattetrekk
    - name: LINK_FAMILIEFORHOLD
      value: https://pensjon-selvbetjening-familieforhold-frontend-veileder-q2.intern.dev.nav.no/pensjon/selvbetjening/familieforhold/?context=ut&pid=PID
    - name: LINK_FULLMAKTER
      value: https://www.intern.dev.nav.no/person/pdl-fullmakt-ui
    - name: LINK_ETTERSENDE
      value: https://www.ansatt.dev.nav.no/ettersende#uforetrygd
    - name: LINK_SAKSBEHANDLINGSTIDER_UFORETRYGD
      value: https://www.ansatt.dev.nav.no/saksbehandlingstider#uforetrygd
    - name: LINK_DITT_LOKALE_NAV_KONTOR
      value: https://www.ansatt.dev.nav.no/no/nav-og-samfunn/kontakt-nav/relatert-informasjon/finn-ditt-nav-kontor
    - name: LINK_REGELVERKSENDRINGER
      value: https://www.nav.no/regelendring-uforetrygd
    - name: LINK_DOKUMENTOVERSIKT
      value: https://www.ansatt.dev.nav.no/dokumentarkiv
    - name: LINK_REPRESENTASJON_TILLEGGSDATA
      value: https://veileder.ansatt.dev.nav.no/representasjon-tilleggsdata?pid=PID
    - name: DIN_UFORETRYGD_BACKEND_SCOPE
      value: api://dev-gcp.ufore.din-uforetrygd-backend/.default
    - name: UFORE_VARSLER_SCOPE
      value: api://dev-gcp.ufore.ufore-varsler/.default
    - name: UNLEASH_SERVER_API_URL
      value: https://ufore-unleash-api.nav.cloud.nais.io/api
    - name: FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
  envFrom:
    - secret: din-uforetrygd-frontend-unleash-api-token
