import { unstable_noStore as noStore } from 'next/cache'

export type Env =
  | 'DECORATOR_ENV'
  | 'MODE'
  | 'UFORETRYGD_BACKEND'
  | 'LINK_SOKNAD_GRADERT_UFORE'
  | 'LINK_SOKNAD_UFORE'
  | 'LINK_SOKNAD_BARNETILLEGG'
  | 'LINK_LES_MER_OM_UFORETRYGD'
  | 'LINK_ENDRE_KONTONUMMER'
  | 'LINK_PERSONOPPLYSNINGER'
  | 'LINK_OKONOMISKE_TILLEGG'
  | 'LINK_KLAGE'
  | 'LINK_UTBETALINGER'
  | 'LINK_BREV'
  | 'LINK_INNTEKTSPLANLEGGER'
  | 'LINK_SAKER'
  | 'LINK_SKATTETREKK'
  | 'LINK_FAMILIEFORHOLD'
  | 'LINK_FULLMAKTER'
  | 'LINK_BPROF_FULLMAKTER'
  | 'LINK_ETTERSENDE'
  | 'LINK_DOKUMENTOVERSIKT'
  | 'LINK_MELD_FRA_OM_ENDRINGER'
  | 'BACKEND_DIN_UFORETRYGD_SCOPE'
  | 'LINK_SAKSBEHANDLINGSTIDER_UFORETRYGD'
  | 'LINK_DITT_LOKALE_NAV_KONTOR'
  | 'REPRESENTASJON_BANNER'

export default function getEnv(env: Env) {
  noStore()
  return process.env[env]
}
