apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uforetrygd-frontend-borger
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  groups:
    - name: uforetrygd-frontend-borger-alerts
      rules:
        - alert: Application is unavailable
          expr: kube_deployment_status_replicas_available{deployment="uforetrygd-frontend-borger"} == 0
          for: 1m
          annotations:
            consequence: Uforetrygd borger application is unavailable
            action: https://logs.adeo.no/app/r/s/GblbS
          labels:
            namespace: pensjonselvbetjening # required
            severity: critical
        - alert: Failing deployment
          expr: kube_deployment_status_replicas_unavailable{deployment="uforetrygd-frontend-borger"} > 1
          for: 5m
          annotations:
            consequence: Uforetrygd borger failing deployment
            action: https://logs.adeo.no/app/r/s/GblbS
          labels:
            namespace: pensjonselvbetjening # required
            severity: critical
