apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: uforetrygd-frontend-veileder
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{ image }}"
  ingresses:
    - https://uforetrygd-selvbetjening-frontend-veileder.intern.dev.nav.no/uforetrygd/selvbetjening
    - https://uforetrygd-selvbetjening-frontend-veileder.ansatt.dev.nav.no/uforetrygd/selvbetjening

  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /uforetrygd/selvbetjening/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /uforetrygd/selvbetjening/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  #  frontend:
  #    generatedConfig:
  #      mountPath: /usr/share/nginx/html/assets/nais.js
  azure:
    sidecar:
      autoLogin: true
      enabled: true
    application:
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "9e122ddd-e542-4cc1-a7eb-92c99140fe0e" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "05ae245b-7b47-428a-9074-4ff6b59eddbc" # 0000-GA-Pensjon_Okonomi
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "a3f91493-1ab8-4b64-a544-0a77cbba9240" # 0000-GA-Pensjon_VEILEDER
          - id: "02505029-3f2e-48a9-b2a8-ff274dacca52" # 0000-GA-PENSJON_KLAGEBEH
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
      enabled: true
      tenant: trygdeetaten.no

  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator # only in dev
          namespace: aura
          cluster: dev-gcp
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: uforetrygd-backend
          cluster: dev-gcp
          namespace: pensjonselvbetjening
  env:
    - name: MODE
      value: veileder
    - name: DECORATOR_ENV
      value: dev
    - name: UFORETRYGD_BACKEND
      value: http://uforetrygd-backend:8080
    - name: LINK_SOKNAD_GRADERT_UFORE
      value: "#GRADERT_UFORE"
    - name: LINK_SOKNAD_UFORE
      value: "#UFORE"
    - name: LINK_SOKNAD_BARNETILLEGG
      value: "#BARNETILLLEGG"
    - name: LINK_LES_MER_OM_UFORETRYGD
      value: "#LES_MER_OM_UFORETRYGD"
    - name: LINK_ENDRE_KONTONUMMER
      value: "#KONTONR"
    - name: LINK_PERSONOPPLYSNINGER
      value: "#PERSONOPPLYSNINGER"
    - name: LINK_OKONOMISKE_TILLEGG
      value: "#OKONOMISKE_TILLEGG"
    - name: LINK_KLAGE
      value: "#KLAGE"
    - name: BACKEND_DIN_UFORETRYGD_SCOPE
      value: "dev-gcp:pensjonselvbetjening:uforetrygd-backend"
