export const mapHendelseCode = (input: string, sakstype: string): string | undefined => {
  const hendelsestype = {
    AFP_EO: 'AFP etteroppgjør',
    ANKE: 'Ankebehandling',
    ANKEBEH_AVSLUTTET: 'Ankebehandling avsluttet',
    ANKE_I_TR_AVSLUTTET: 'Ankebehandling i trygderetten avsluttet',
    ANKE_I_TR_OPPRETTET: 'Ankebehandling i trygderetten opprettet',
    ANKE_OPPRETTET: 'Anke opprettet',
    ANNULERING: 'Annulering av behandling',
    AUTO_OMR_UP_TIL_UT: 'Automatisk omregning til uføretrygd',
    EKSPORT: 'Eksport av ytelse',
    ENDR_UTBET: 'Endret utbetalingsopplysninger',
    ENDR_UTTAKSGRAD: 'Endring uttaksgrad',
    ERSTATNING: 'Behandling av erstatning',
    ETTERGIV_GJELD: 'Ettergivelse av gjeld',
    FAS_UTG_IO: 'Dekning av faste utgifter til institusjons opphold',
    FEILUTBT: 'Behandling av feilutbetaling',
    FORSTEG_BH: 'Startet behandling av ' + sakstype,
    F_BH_BO_UTL: 'Startet behandling av ' + sakstype,
    F_BH_KUN_UTL: 'Startet behandling av ' + sakstype,
    F_BH_MED_UTL: 'Startet behandling av ' + sakstype,
    GJ_RETT: 'Behandling av gjenlevenderettighet',
    GOD_OMSGSP: 'Godskrivning av omsorgspoeng',
    GOMR: 'Regulering av ' + sakstype,
    GOMRFAKT: 'Regulering av ' + sakstype,
    HOVED_OPPHORT: 'Ytelse opphørt',
    INNT_E: 'Inntektsendring',
    INNT_KTRL: 'Inntektskontroll',
    KLAGE: 'Klagebehandling',
    KONVERTERING: 'Aldersomregning',
    MELLOMBH: 'Mellombehandling',
    MOTTATT_UTLAND: 'Mottatt svar fra utland',
    OMGJ_FEILUTBT: 'Omgjøring av feilutbetaling',
    OMGJ_TILBAKE: 'Omgjøring av tilbakekreving',
    OMREGNET: 'Automatisk omregnet',
    OMREGNET_TIL_UT: 'Automatisk omregnet fra uførepensjon til uføretrygd',
    OMR_FAK_UT: 'Automatisk omregnet fra uførepensjon til uføretrygd',
    OVERF_OMSGSP: 'Overføring av omsorgspoeng',
    REBEREGNET: 'Ny automatisk beregning ved aldersovergang',
    REBER_ANNEN_SAK: 'Beregnet på nytt på grunn av avhengighet til annen sak',
    REGULERING: 'Regulering av pensjon',
    REGULERINGFAKT: 'Regulering av pensjon',
    REVURD: 'Revurdering',
    SAK_OMKOST: 'Saksomkostninger',
    SAK_OPPRETTET: 'Sak opprettet',
    SENDT_SAM_MELD: 'Sendt til samordning hos offentlig tjenestepensjonsordning',
    SENDT_UTLAND: 'Sendt henvendelse til utland',
    SLUTT_BH_UTL: 'Sluttbehandling utland',
    SOK_OKN_UG: 'Søknad om økning av uføregrad',
    SOK_RED_UG: 'Søknad om reduksjon av uføregrad',
    SOK_UU: 'Søknad om ung ufør',
    SOK_YS: 'Søknad om yrkesskade',
    TILBAKEKR: 'Behandling av tilbakekreving',
    TILLEGG_OPPHORT: 'Tilleggsytelse opphørt',
    UT_EO: 'Etteroppgjør',
    UT_VURDERING_EO: 'Vurdering av etteroppgjør',
    VEDTAK_FATTET: 'Vedtak fattet',
    VEDTAK_REAK: 'Vedtak reaktivert',
    VEDTAK_STOPPET: 'Vedtak stoppet',
    VURDERT_OMREGNING: 'Vurdert for omregning ved tilvekst i opptjening',
    IKKE_AVVIK_UTEO: 'Etteroppgjør ferdig. Ingen avvik funnet',
    TILBAKEKR_TOLGR_UTEO: 'Etteroppgjør ferdig. Ingen tilbakekreving nødvendig',
    ETTERBET_TOLGR_UTEO: 'Etteroppgjør ferdig. Ingen etterbetaling',
    IKKE_AVKORT_UTEO: 'Uføretrygden er ikke avkortet mot inntekt.',
    DOD_I_EOARET_UT: 'Bruker døde i etteroppgjørsåret.',
    DOD_ETTER_EOARET_UT: 'Bruker døde året etter etteroppgjørsåret eller senere.',
    FEILREG_EO_UT: 'Feilregistrert vurderingskrav i forbindelse med opprettelse av løpende etteropppgjørskrav.',
    UTSEND_AVTALELAND: 'Utsendelse til avtaleland',
    FEILREG_REKJOR_EO_UT: 'Feilregistrert vurderingskrav i forbindelse med at etteropppgjøret skal kjøres på nytt',
    SLUTTBEH_KUN_UTL: 'Sluttbehandling kun utland',
    INFOBREV_SENDES_UT: 'Infobrev om forventet årlig arbeidsinntekt er sendt til deg',
  }

  return hendelsestype[input as keyof typeof hendelsestype]
}

export const mapKravGjelderCode = (input: string, sakstype: string): string => {
  const kravGjelder = {
    AFP_EO: 'AFP etteroppgjør',
    ANKE: 'Anke',
    EKSPORT: 'Eksport av ' + sakstype,
    ENDR_UTTAKSGRAD: 'Endring uttaksgrad',
    // ERSTATNING: 'Erstatning',
    ETTERGIV_GJELD: 'Ettergivelse av gjeld',
    // FAS_UTG_IO: 'Dekning faste utgifter inst.opphold',
    FORSTEG_BH: 'Søknad om ' + sakstype,
    F_BH_BO_UTL: 'Søknad om ' + sakstype,
    F_BH_KUN_UTL: 'Søknad om ' + sakstype,
    F_BH_MED_UTL: 'Søknad om ' + sakstype,
    // GJ_RETT: 'Gjenlevenderettighet',
    GOD_OMSGSP: 'Godskriving omsorgsopptjening',
    // GOMR: 'G-omregning',
    //HJLPBER_OVERG_UT: 'Hjelpeberegning ved overgang til uføretrygd',
    INNT_E: 'Inntektsendring',
    // INNT_KTRL: 'Inntektskontroll',
    KLAGE: 'Klage',
    KONTROLL_3_17_A: 'Kontroll 3-17 a',
    // KONVERTERING: 'Konvertert krav',
    // KONVERTERING_MIN: 'Minimalt konvertert krav',
    // KONV_AVVIK_G_BATCH: 'Konvertering - Avvik ved G-omr',
    // MELLOMBH: 'Mellombehandling',
    // MTK: 'Merskatt tilbakekreving',
    OMGJ_TILBAKE: 'Omgjøring av tilbakekreving',
    OVERF_OMSGSP: 'Overføring omsorgsopptjening',
    REGULERING: 'Regulering',
    REVURD: 'Saksgjennomgang',
    SAK_OMKOST: 'Behandling relatert til saksomkostninger',
    SLUTT_BH_UTL: 'Sluttbehandling Norge/utland',
    SOK_OKN_UG: 'Endring av uføregrad',
    SOK_RED_UG: 'Endring av uføregrad',
    SOK_UU: 'Søknad om ung ufør',
    SOK_YS: 'Søknad om yrkesskade',
    TILBAKEKR: 'Tilbakekreving',
    UT_EO: 'Etteroppgjør uføretrygd',
    UT_VURDERING_EO: 'Vurdering av etteroppgjør',
    UTSEND_AVTALELAND: 'Sendt krav til avtaleland',
    SLUTTBEH_KUN_UTL: 'Sluttbehandling kun utland',
  }

  return kravGjelder[input as keyof typeof kravGjelder]
}

export const mapKravArsakCode = (input: string): string => {
  const kravArsak = {
    AFP_EO: 'AFP etteroppgjør',
    ALDERSOVERGANG: 'Aldersovergang',
    ANNEN_ARSAK: 'Annen årsak til saksbehandling',
    ANNEN_ARSAK_END_IN: 'Annen årsak til inntektsendring',
    ANNEN_FOR_END_IN: 'Annen forelder har endret inntekt',
    BARN_DOD: 'Dødsfall barn',
    BARN_ENDRET_INNTEKT: 'Inntekt til barn er endret',
    BEGGE_FOR_END_IN: 'Begge forsørgerne har endret inntekt',
    BEREGNING: 'Beregning',
    ENDRET_INNTEKT: 'Inntekt til bruker er endret',
    ENDRET_OPPTJENING: 'Opptjeningsgrunnlag er endret',
    ENDRING_IFU: 'Endring av IFU',
    ENDR_ANNEN_SAK: 'Bruker har annen sak som er endret',
    EPS_ENDRET_INNTEKT: 'Inntekt til tilstøtende er endret',
    EPS_NY_YTELSE: 'Tilstøtende har fått innvilget pensjon',
    EPS_NY_YTELSE_UT: 'Tilstøtende har fått innvilget uføretrygd',
    EPS_OPPH_YTELSE_UT: 'Tilstøtende sin uføretrygd er opphørt',
    GJNL_SKAL_VURD: 'Gjenlevendetilegg skal vurderes',
    GODSKR_OVERF: 'Godskriving/overføring',
    GOMR: 'G-omregning',
    HJEMMEBER_FOR_UT: 'Hjemmeberegning for uføretrygd',
    INNT_KONTROLL: 'Inntektskontroll',
    INNVANDRET: 'Innvandring',
    INSTOPPHOLD: 'Institusjonsopphold på bruker/tilstøtende',
    KLAGE_ANKE: 'Klage/anke',
    KONTR_3_17: 'Kontroll 3-17 a',
    LOVVALG: 'Nye opplysninger på bruker',
    NYE_OPPLYSNINGER: 'Lovvalg',
    NY_SOKNAD: 'Ny søknad',
    OMGJ_ETTER_ANKE: 'Omgjøring etter anke',
    OMGJ_ETTER_KLAGE: 'Omgjøring etter klage',
    OMGJ_ETTER_FVL_P35_A: 'Omgjøring fvl. § 35 første ledd bokstav a',
    OMGJ_ETTER_FVL_P35_B: 'Omgjøring fvl. § 35 første ledd bokstav b',
    OMGJ_ETTER_FVL_P35_C: 'Omgjøring fvl. § 35 første ledd bokstav c',
    OMREGN_UFORETRYGD: 'Omregning til uføretrygd',
    OPPHOR: 'Opphør av brukers ytelse',
    OPPL_UTLAND: 'Opplysninger fra utlandet',
    REGULERING: 'Regulering av brukers ytelse',
    REKONSTRUKSJON: 'Rekonstruksjon',
    SIVILSTANDSENDRING: 'Sivilstandsendring',
    TILBAKEKREVING: 'Tilbakekreving',
    TILSTOT_ENDR_YTELSE: 'Tilstøtende sin sak er endret',
    TILSTOT_OPPHORT: 'Opphør av tilstøtendes ytelse',
    TILST_DOD: 'Dødsfall tilstøtende',
    UFOREBER_V_GTGRD: 'Uføreberegning ved garantigrad',
    UFOREBER_V_TIDUFT: 'Uføreberegning ved tidl. Uføretrygd',
    UFOREOVERGANG: 'Uføretrygdovergang',
    UTTAKSGRAD: 'Uttaksgrad er endret eller oppdatert',
    UTVANDRET: 'Utvandring/eksport',
    UT_EO: 'Etteroppgjør',
    UT_VURDERING_EO: 'Vurdering Etteroppgjør',
    VURDER_FORSORG: 'Forsørgingstillegg skal vurderes',
    VURD_SIVILST: 'Avvik i vurdert sivilstand for berørte saker',
    AVSLAG_UT: 'Avslag uføretrygd',
    AVSLAG: 'Avslag',
    AVSLAG_INVAL_ENKEP: 'Avslag (Invalide-/eller enkepensjon)',
    AVSLAG_UNG_UFR: 'Avslag ung ufør',
    BARN_UTDS_FLYTTEUTG: 'Barnetilsyn/utd.stønad/flytteutg.',
    BARNETILLEGG: 'Barnetillegg',
    EKSPORT: 'Eksport',
    EKTEFELLETILLEGG: 'Ektefelletillegg',
    ETTEROPPGJOR: 'Etteroppgjør',
    GJENLEVENDERETT: 'Gjenlevenderett',
    GJENLEVENDETILLEGG: 'Gjenlevendetillegg',
    GRADSENDRINGER: 'Gradsendringer',
    HVIL_STONADSRETT: 'Hvilende stønadsrett',
    MEDISINSK_STONAD: 'Medisinsk støtte',
    MEDL_TRYGDETID: 'Medlemskap/trygdetid',
    MEDL_TRYGDETID_OPPTJ: 'Medlemskap/trygdetid/opptjening',
    OMSORG_FOR_SMA_BARN: 'Omsorg for små barn',
    OPPHOR_HJELPELOS: 'Opphør av hjelpeløshetbidrag',
    OPPHOR_RED_UFG: 'Opphør/reduksjon uføregrad',
    OPPHOR_REDUKSJON: 'Opphør/reduksjon',
    OPPHOR_TLG_HJELP_HUS: 'Opphør av tillegg til hjelp i huset',
    OPPTJENINGSGRUNNLAG: 'Opptjeningsgrunnlag',
    OVERGANGSSTONAD: 'Overgangsstønad',
    OVRFR_OMSORGSPOENG: 'Overføring av omsorgsopptjening',
    PENSJONSVILKAR: 'Pensjonsvilkår',
    PLEIE_ELDR_SYK_FUNK: 'Pleie eldre/syke/funksjonshemmede',
    SAMORDNING: 'Samordning',
    TIDLIGUTTAK: 'Tidliguttak',
    UFG_IFU_OG_IEU: 'Uføregrad/IFU og IEU',
    UFR_GRAD: 'Uføregrad',
    UFR_PENSJON_GRAD: 'Uføre-/pensjonsgrad',
    UFR_TIDSPUNKT: 'Uføretrygd tidspunkt',
    UTBET_AVKORT: 'Utbetaling/avkortning',
    VILKAR: 'Vilkår',
    VIRK_TIDSPUNKT: 'Virkningstidspunkt',
    YRK_SKADE_SYK: 'Yrkesskade/-sykdom',
    YRKESSKADE: 'Yrkesskade',
    ANNET: 'Annet',
    BODD_ARB_UTL: 'Bodd/arbeidet i avtaleland',
    UT_OMGJ_ANKE_EO: 'Omgjøring etter anke',
    UT_OMGJ_KLAGE_EO: 'Omgjøring etter klage',
    SOKNAD_BT: 'Søknad om barnetillegg',
    OMREGNING: 'Omregning pga regelendring',
    OMR_FEILRETTING: 'Omregning etter feilretting',
    VURDER_SERSKILT_SATS: 'Særskilt sats for forsørger skal vurderes',
  }

  return kravArsak[input as keyof typeof kravArsak]
}
