query dokumentoversiktFagsak($fagsak: FagsakInput!, $foerste: Int!) {
    dokumentoversiktFagsak(fagsak: $fagsak, foerste:$foerste) {
        journalposter {
            sak {
                fagsakId
            }
            tittel
            journalpostId
            tema
            avsenderMottaker {
                id
                erLikBruker
            }
            datoOpprettet
            brukerHarTilgang
            dokumenter {
                tittel
                dokumentInfoId
                dokumentvarianter {
                    brukerHarTilgang
                    filtype
                }
            }
        }
    }
}