name: "Dev: Uforetrygd frontend deploy"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * SUN"

jobs:
  build-frontend-and-publish-docker:
    name: Bygg din-uforetrygd-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./din-uforetrygd-frontend/
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bruk node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          cache-dependency-path: din-uforetrygd-frontend/package-lock.json

      - name: Installer avhengigheter
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Bygg med node
        run: npm run build

      - name: Prune dev-avhengigheter
        run: npm prune --production

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ufore
          dockerfile: ./din-uforetrygd-frontend/.docker/Dockerfile
          image_suffix: din-uforetrygd-frontend


  deploy-frontend-borger-dev:
    needs: build-frontend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: uforetrygd-frontend/.nais/dev-borger.yml
          IMAGE: ${{ needs.build-frontend-and-publish-docker.outputs.image }}
          TEAM: ufore


  deploy-frontend-veileder-dev:
    needs: build-frontend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: uforetrygd-frontend/.nais/dev-veileder.yml
          IMAGE: ${{ needs.build-frontend-and-publish-docker.outputs.image }}
          TEAM: ufore