name: "Prod: Din uforetrygd backend deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - din-uforetrygd-backend/**

concurrency:
  group: prod-din-uforetrygd-backend-deploy
  cancel-in-progress: true

jobs:
  build-backend-and-publish-docker:
    name: Bygg backend application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: cd ./din-uforetrygd-backend && mvn -B package --file pom.xml

      - name: docker-build-push
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-build-push
        with:
          team: ufore
          dockerfile: ./din-uforetrygd-backend/Dockerfile
          image_suffix: din-uforetrygd-backend

      - name: "Send slack-notifikasjon om bygget feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Bygg av din-uforetrygd-backend til deploy til prod feilet* :bomb::broken_heart:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  trivy-docker:
    needs: build-backend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
        with:
          team: ufore
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          image-ref: ${{ needs.build-backend-and-publish-docker.outputs.image }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4.37.2
        with:
          sarif_file: 'trivy.sarif'

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-backend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Deploy
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: din-uforetrygd-backend/.nais/prod.yml
          IMAGE: ${{ needs.build-backend-and-publish-docker.outputs.image }}
          TEAM: ufore
      - name: "Send slack-notifikasjon om deploy feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Deploy av din-uforetrygd-backend til prod feilet* :bomb::this-is-fine-fire: \nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}