name: "Prod: Din uforetrygd backend deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - din-uforetrygd-backend/**

concurrency:
  group: prod-din-uforetrygd-backend-deploy
  cancel-in-progress: true

jobs:
  build-backend-and-publish-docker:
    name: Bygg backend application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: cd ./din-uforetrygd-backend && mvn -B package --file pom.xml

      - name: docker-build-push
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # v0
        id: docker-build-push
        with:
          team: ufore
          dockerfile: ./din-uforetrygd-backend/Dockerfile
          image_suffix: din-uforetrygd-backend

      - name: "Send slack-notifikasjon om bygget feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Bygg av din-uforetrygd-backend til deploy til prod feilet* :bomb::broken_heart:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  trivy-docker:
    needs: build-backend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # v0
        with:
          team: ufore
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          image-ref: ${{ needs.build-backend-and-publish-docker.outputs.image }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba # v4.35.5
        with:
          sarif_file: 'trivy.sarif'

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-backend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Deploy
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: din-uforetrygd-backend/.nais/prod.yml
          IMAGE: ${{ needs.build-backend-and-publish-docker.outputs.image }}
          TEAM: ufore
      - name: "Send slack-notifikasjon om deploy feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Deploy av din-uforetrygd-backend til prod feilet* :bomb::this-is-fine-fire: \nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}