name: "Prod: Din uforetrygd backend deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - din-uforetrygd-backend/**

jobs:
  build-backend-and-publish-docker:
    name: Bygg backend application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: cd ./din-uforetrygd-backend && mvn -B package --file pom.xml

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ufore
          dockerfile: ./din-uforetrygd-backend/Dockerfile
          image_suffix: din-uforetrygd-backend

      - name: "Send slack-notifikasjon om bygget feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Deploy av din-uforetrygd-backend til prod feilet* :bomb:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/pesys/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  trivy-docker:
    needs: build-backend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: nais/login@v0
        with:
          team: ufore
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-backend-and-publish-docker.outputs.image }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy.sarif'

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-backend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: din-uforetrygd-backend/.nais/prod.yml
          IMAGE: ${{ needs.build-backend-and-publish-docker.outputs.image }}
          TEAM: ufore