name: "Prod: Din uforetrygd frontend deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - din-uforetrygd-frontend/**

concurrency:
  group: prod-din-uforetrygd-frontend-deploy
  cancel-in-progress: true

jobs:
  build-frontend-and-publish-docker:
    name: Bygg din-uforetrygd-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./din-uforetrygd-frontend/
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bruk node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          cache-dependency-path: din-uforetrygd-frontend/package-lock.json

      - name: Installer avhengigheter
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Lint
        run: npm run check

      - name: Bygg med node
        run: npm run build

      - name: Prune dev-avhengigheter
        run: npm prune --production

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ufore
          dockerfile: ./din-uforetrygd-frontend/.docker/Dockerfile
          image_suffix: din-uforetrygd-frontend

      - name: "Send slack-notifikasjon om bygget feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Bygg av din-uforetrygd-frontend til deploy til prod feilet* :bomb::hellmo:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  trivy-docker:
    needs: build-frontend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: nais/login@v0
        with:
          team: ufore
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: ${{ needs.build-frontend-and-publish-docker.outputs.image }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4.35.1
        with:
          sarif_file: 'trivy.sarif'

  deploy-frontend-borger-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-frontend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: din-uforetrygd-frontend/.nais/prod-borger.yml,din-uforetrygd-frontend/.nais/unleash-prod.yml
          IMAGE: ${{ needs.build-frontend-and-publish-docker.outputs.image }}
          TEAM: ufore
      - name: "Send slack-notifikasjon om deploy til borger feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Deploy av din-uforetrygd-frontend-borger til prod feilet* :bomb::fire:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}


  deploy-frontend-veileder-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-frontend-and-publish-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: din-uforetrygd-frontend/.nais/prod-veileder.yml,din-uforetrygd-frontend/.nais/unleash-prod.yml
          IMAGE: ${{ needs.build-frontend-and-publish-docker.outputs.image }}
          TEAM: ufore
      - name: "Send slack-notifikasjon om deploy til veileder feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \"*Deploy av din-uforetrygd-frontend-veileder til prod feilet* :bomb:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/din-uforetrygd/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
